name: AlphaTrak-Failover
on:
  workflow_dispatch:
jobs:
  SQLServer1_Failover:    
      uses: SNawazmac/sql_failover/.github/workflows/sql_failover.yml@main
      with:
        secondary_mssql_server_resource_group_name: ${{ vars.SECONDARY_MSSQL_SERVER_RESOURCE_GROUP_NAME }} 
        secondary_mssql_server_name: ${{ vars.SECONDARY_MSSQL_SERVER_NAME_1 }} 
        secondary_mssql_server_subscription_Id:  ${{ vars.SECONDARY_MSSQL_SERVER_SUBSCRIPTION_ID }} 
        failover_group_name: ${{ vars.FAILOVER_GROUP_NAME_1 }} 
      secrets:
        AZURE_CREDENTIALS_DELOITTE_SUB : ${{ secrets.AZURE_CREDENTIALS_DELOITTE_SUB }} 
 
  StorageAccount_Invoke_Failover:    
      uses: SNawazmac/storage_account_failover/.github/workflows/storage_with_dns_failover.yml@main
      with:
        storage_account_resource_group_name: ${{ vars.STORAGE_ACCOUNT_RESOURCE_GROUP_NAME }} #changed variable name
        private_storage_account_names: ${{ vars.PRIVATE_STORAGE_ACCOUNT_NAMES }} 
        sku:  ${{ vars.STORAGE_SKU }}
        
  Link_Private_Endpoint_to_DNS:
      needs: StorageAccount_Invoke_Failover
      uses:  SNawazmac/storage_account_failover/.github/workflows/storage_with_dns_failover.yml@main
      with:  
        private_dns_zone_subscription_Id: ${{ vars.PRIVATE_DNS_ZONE_SUBSCRIPTION_ID }}
        secondary_private_endpoint_subscription_Id: ${{ vars.SECONDARY_PRIVATE_ENDPOINT_SUBSCRIPTION_ID }}
        private_dns_zone_resource_group_name: ${{ vars.PRIVATE_DNS_ZONE_RESOURCE_GROUP_NAME }}
        secondary_private_endpoint_resource_group_name: ${{ vars.SECONDARY_PRIVATE_ENDPOINT_RESOURCE_GROUP_NAME }}
        secondary_private_endpoint_name: ${{ vars.STORAGE_ACCOUNT_1_SECONDARY_PRIVATE_ENDPOINT_NAME }}
        storage_account_private_dns_zone_name: ${{ vars.STORAGE_ACCOUNT_PRIVATE_DNS_ZONE_NAME }}
        storage_account_private_dns_zone_group_name: ${{ vars.STORAGE_ACCOUNT_PRIVATE_DNS_ZONE_GROUP_NAME }}
      secrets:
        AZURE_CREDENTIALS_DELOITTE_SUB : ${{ secrets.AZURE_CREDENTIALS_DELOITTE_SUB }}
        
  Keyvault_DNS_Failover: 
      uses: SNawazmac/key_vault_dns_failover/.github/workflows/key_vault_dns_failover.yml@main
      with:
        primary_subscription_Id: ${{ vars.PRIVATE_DNS_ZONE_SUBSCRIPTION_ID }}
        secondary_private_endpoint_subscription_Id: ${{ vars.SECONDARY_PRIVATE_ENDPOINT_SUBSCRIPTION_ID }}
        private_dns_zone_resource_group_name: ${{ vars.PRIVATE_DNS_ZONE_RESOURCE_GROUP_NAME }}
        secondary_private_endpoint_resource_group_name: ${{vars.SECONDARY_PRIVATE_ENDPOINT_RESOURCE_GROUP_NAME }}
        secondary_private_endpoint_name: ${{ vars.KEY_VAULT_1_SECONDARY_PRIVATE_ENDPOINT_NAME }}
        key_vault_private_dns_zone_name: ${{ vars.KEY_VAULT_PRIVATE_DNS_ZONE_NAME }}
        key_vault_private_dns_zone_group_name: ${{ vars.KEY_VAULT_PRIVATE_DNS_ZONE_GROUP_NAME }}
      secrets:
        AZURE_CREDENTIALS_DELOITTE_SUB : ${{ secrets.AZURE_CREDENTIALS_DELOITTE_SUB }}      
