name: AlphaTrak-Failback
on:
  workflow_dispatch:
jobs:
  SQLServer1_Failback:    
      uses: SNawazmac/sql_failback/.github/workflows/Invoke_sql_failback.yml@main
      with:
        primary_mssql_server_resource_group_name: ${{ vars.PRIMARY_MSSQL_SERVER_RESOURCE_GROUP_NAME }} 
        primary_mssql_server_name: ${{ vars.PRIMARY_MSSQL_SERVER_NAME_1 }} 
        primary_mssql_server_subscription_Id:  ${{ vars.PRIMARY_MSSQL_SERVER_SUBSCRIPTION_ID }} 
        failover_group_name: ${{ vars.FAILOVER_GROUP_NAME_1 }} 
      secrets:
        AZURE_CREDENTIALS_DELOITTE_SUB : ${{ secrets.AZURE_CREDENTIALS_DELOITTE_SUB }}
 
  StorageAccount_Invoke_Failback:    
      uses: SNawazmac/storage_account_failback/.github/workflows/storage_account_invoke_failback.yml@main
      with:
        storage_account_resource_group_name: ${{ vars.STORAGE_ACCOUNT_RESOURCE_GROUP_NAME }} #changed variable name
        private_storage_account_names: ${{ vars.PRIVATE_STORAGE_ACCOUNT_NAMES }} 
        sku:  ${{ vars.STORAGE_SKU }}
      secrets:
        AZURE_CREDENTIALS_DELOITTE_SUB : ${{ secrets.AZURE_CREDENTIALS_DELOITTE_SUB }}
        
  StorageAccount_1_Update_dns_record:
      needs: StorageAccount_Invoke_Failback
      uses: SNawazmac/storage_account_failback/.github/workflows/storage_account_dns_failback.yml@main
      with:
        private_dns_zone_subscription_Id: ${{ vars.PRIVATE_DNS_ZONE_SUBSCRIPTION_ID }}
        private_dns_zone_resource_group_name: ${{ vars.PRIVATE_DNS_ZONE_RESOURCE_GROUP_NAME }} # this should be considered not above
        storage_account_private_dns_zone_record_name: ${{ vars.STORAGE_ACCOUNT_1_PRIVATE_DNS_ZONE_RECORD_NAME }}
        storage_account_private_dns_zone_name: ${{ vars.STORAGE_ACCOUNT_PRIVATE_DNS_ZONE_NAME }}
        storage_account_primary_private_endpoint_IP: ${{ vars.STORAGE_ACCOUNT_1_PRIMARY_PRIVATE_ENDPOINT_IP }}
        storage_account_secondary_private_endpoint_IP: ${{ vars.STORAGE_ACCOUNT_1_SECONDARY_PRIVATE_ENDPOINT_IP }}
      secrets:
        AZURE_CREDENTIALS_DELOITTE_SUB : ${{ secrets.AZURE_CREDENTIALS_DELOITTE_SUB }}
        
  Keyvault_DNS_Failback: 
      uses: SNawazmac/key_vault_dns_failback/.github/workflows/key_vault_with_dns_failback.yml@main
      with:
        primary_subscription_Id: ${{ vars.PRIVATE_DNS_ZONE_SUBSCRIPTION_ID }}
        private_dns_zone_resource_group_name: ${{ vars.PRIVATE_DNS_ZONE_RESOURCE_GROUP_NAME }} # this should be considered not above
        key_vault_private_dns_zone_record_name: ${{ vars.KEY_VAULT_1_PRIVATE_DNS_ZONE_RECORD_NAME }}
        key_vault_private_dns_zone_name: ${{ vars.KEY_VAULT_PRIVATE_DNS_ZONE_NAME }}
        key_vault_primary_private_endpoint_IP: ${{ vars.KEY_VAULT_1_PRIMARY_PRIVATE_ENDPOINT_IP }}
        key_vault_secondary_private_endpoint_IP: ${{ vars.KEY_VAULT_1_SECONDARY_PRIVATE_ENDPOINT_IP }}
        
      secrets:
        AZURE_CREDENTIALS_DELOITTE_SUB : ${{ secrets.AZURE_CREDENTIALS_DELOITTE_SUB }}      
