name: container_Failback_second_run
on:
  workflow_dispatch:
jobs:
 container_Failback_run:
      uses:  SNawazmac/container_registry_dns_failback/.github/workflows/container_registry_dns_failback.yml@main
      with:  
        private_dns_zone_subscription_Id: ${{ vars.PRIVATE_DNS_ZONE_SUBSCRIPTION_ID }}
        private_dns_zone_resource_group_name: ${{ vars.PRIVATE_DNS_ZONE_RESOURCE_GROUP_NAME }}
        container_registry_private_dns_zone_global_record_name: ${{ vars.CONTAINER_REGISTRY_PRIVATE_DNS_ZONE_GLOBAL_RECORD_NAME }}
        container_registry_private_dns_zone_primary_region_record_name: ${{ vars.CONTAINER_REGISTRY_PRIVATE_DNS_ZONE_PRIMARY_RECORD_NAME }}
        container_registry_private_dns_zone_secondary_region_record_name: ${{ vars.CONTAINER_REGISTRY_PRIVATE_DNS_ZONE_SECONDARY_RECORD_NAME }}
        container_registry_global_endpoint_primary_region_IP: ${{ vars.CONTAINER_REGISTRY_GLOBAL_ENDPOINT_PRIMARY_REGION_IP }}
        container_registry_global_endpoint_secondary_region_IP: ${{ vars.CONTAINER_REGISTRY_GLOBAL_ENDPOINT_SECONDARY_REGION_IP }}
        container_registry_primary_endpoint_primary_region_IP: ${{ vars.CONTAINER_REGISTRY_PRIMARY_ENDPOINT_PRIMARY_REGION_IP }}
        container_registry_primary_endpoint_secondary_region_IP: ${{ vars.CONTAINER_REGISTRY_PRIMARY_ENDPOINT_SECONDARY_REGION_IP }}
        container_registry_secondary_endpoint_primary_region_IP: ${{ vars.CONTAINER_REGISTRY_SECONDARY_ENDPOINT_PRIMARY_REGION_IP }}
        container_registry_secondary_endpoint_secondary_region_IP: ${{ vars.CONTAINER_REGISTRY_SECONDARY_ENDPOINT_SECONDARY_REGION_IP }}
        container_registry_private_dns_zone_name: ${{ vars.CONTAINER_REGISTRY_PRIVATE_DNS_ZONE_NAME }}
      secrets:
        AZURE_CREDENTIALS_DELOITTE_SUB : ${{ secrets.AZURE_CREDENTIALS_DELOITTE_SUB }}
