name: cosmosdb_failover
on:
  workflow_dispatch:
jobs:
 Invoke_cosmosdb_failover:
      uses:  SNawazmac/cosmosdb_failover/.github/workflows/cosmosdb_invoke_failover.yml@main
      with:  
        cosmosdb_resource_group_name: ${{ vars.COSMOSDB_RESOURCE_GROUP_NAME }}
        cosmosdb_name: ${{ vars.COSMOSDB_NAME }}
        cosmosdb_primary_region: ${{ vars.COSMOSDB_PRIMARY_REGION_NAME }}
        cosmosdb_secondary_region: ${{ vars.COSMOSDB_SECONDARY_REGION_NAME }}
      secrets:
        AZURE_CREDENTIALS_DELOITTE_SUB : ${{ secrets.AZURE_CREDENTIALS_DELOITTE_SUB }}
        
  Link_Private_Endpoint_to_DNS:
      uses:  SNawazmac/cosmosdb_failover/.github/workflows/cosmos_db_link_pe_to_dns.yml@main
      with:  
        private_dns_zone_subscription_Id: ${{ vars.PRIVATE_DNS_ZONE_SUBSCRIPTION_ID }}
        secondary_private_endpoint_subscription_Id: ${{ vars.SECONDARY_PRIVATE_ENDPOINT_SUBSCRIPTION_ID }}
        private_dns_zone_resource_group_name: ${{ vars.PRIVATE_DNS_ZONE_RESOURCE_GROUP_NAME }}
        secondary_private_endpoint_resource_group_name: ${{ vars.SECONDARY_PRIVATE_ENDPOINT_RESOURCE_GROUP_NAME }}
        secondary_private_endpoint_name: ${{ vars.COSMOSDB_1_SECONDARY_PRIVATE_ENDPOINT_NAME }}
        cosmosdb_private_dns_zone_name: ${{ vars.COSMOSDB_PRIVATE_DNS_ZONE_NAME }}
        cosmosdb_private_dns_zone_group_name: ${{ vars.COSMOSDB_PRIVATE_DNS_ZONE_GROUP_NAME }}
      secrets:
        AZURE_CREDENTIALS_DELOITTE_SUB : ${{ secrets.AZURE_CREDENTIALS_DELOITTE_SUB }}
