name: data_factory_failover_first_run
on:
  workflow_dispatch:
jobs:  
  data_factory_link_pe_to_dns: 
      uses: SNawazmac/data_factory_dns_failover/.github/workflows/data_factory_link_pe_to_dns.yml@main
      with:
        private_dns_zone_subscription_Id: ${{ vars.PRIVATE_DNS_ZONE_SUBSCRIPTION_ID }}
        secondary_private_endpoint_subscription_Id: ${{ vars.SECONDARY_PRIVATE_ENDPOINT_SUBSCRIPTION_ID }}
        private_dns_zone_resource_group_name: ${{ vars.PRIVATE_DNS_ZONE_RESOURCE_GROUP_NAME }}
        secondary_private_endpoint_resource_group_name: ${{ vars.SECONDARY_PRIVATE_ENDPOINT_RESOURCE_GROUP_NAME }}
        secondary_private_endpoint_name: ${{ vars.DATA_FACTORY_1_SECONDARY_PRIVATE_ENDPOINT_NAME }}
        data_factory_private_dns_zone_name: ${{ vars.DATA_FACTORY_PRIVATE_DNS_ZONE_NAME }}
        data_factory_private_dns_zone_group_name: ${{ vars.DATA_FACTORY_PRIVATE_DNS_ZONE_GROUP_NAME }}
      secrets:
        AZURE_CREDENTIALS_DELOITTE_SUB : ${{ secrets.AZURE_CREDENTIALS_DELOITTE_SUB }}
